#!/usr/bin/env bash
set -eu

EXTRA_ARGS=""
IVY_CACHE=${IVY_CACHE-}
SBT_CACHE=${SBT_CACHE-}
USER_HOME=${USER_HOME-}

if [ -n "$IVY_CACHE" ]; then
	EXTRA_ARGS="-Dsbt.ivy.home=$IVY_CACHE"
fi

if [ -n "$SBT_CACHE" ]; then
	EXTRA_ARGS="$EXTRA_ARGS -Dsbt.boot.directory=$SBT_CACHE"
fi

if [ -n "$USER_HOME" ]; then
	EXTRA_ARGS="$EXTRA_ARGS -Duser.home=$USER_HOME"
fi

sbt -Dsbt.repository.config=repositories -Dsbt.override.build.repos=true -DtestLog.level=INFO $EXTRA_ARGS "$@"
